### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by dupersaurus** [dupersaurus/wush#16]
Implement permission levels to allow users to use extra features.
- **Admin** Administrate users, moderate activity, build worlds and rooms.
- **Builder** Can build worlds and rooms.
- **Verified User** User authorized to play
- **Guest** User with only (limit-able) view access

Setting a user's level automatically applies the associated permissions.

**Comment by jdpdev** [comment]
Define explicit permissions that can be assigned to users individually, or implied by user types (from above). A permission is a type with an optional parameter.
- [ ] (MOD-USER) Modify users
- [ ] (MOD-CHAR) Modify characters
- [ ] (MOD-POSE) Moderate poses
- [ ] (BAN-USER) Ban users
- [ ] (WARN-USER) Probate/warn users
- [ ] (BUILD-WORLD) Build worlds
- [ ] (BUILD-ROOM) Build/edit rooms (optional world id restriction)
- [ ] (SET-MOTD) Set MOTD

**Comment by jdpdev** [comment]
Superseded by #34, #35, and #36
